# Generated by Django 5.2.1 on 2025-05-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('auditores', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Auditor'}, related_name='encuestas_auditor', to=settings.AUTH_USER_MODEL)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supervisores', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Supervisor'}, related_name='encuestas_supervisor', to=settings.AUTH_USER_MODEL)),
                ('tiendas', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Tienda'}, related_name='encuestas_tienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
