# Generated by Django 5.2.1 on 2025-05-14 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_encuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='encuestas_group_assigned', to='auth.group'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='encuestas_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
