# Generated by Django 5.2.1 on 2025-06-03 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_encuesta_assigned_groups_encuesta_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='assigned_groups',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='auditores',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='supervisores',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='tiendas',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='es_correcta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='texto',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ayuda_visual',
            field=models.FileField(blank=True, help_text='Opcional: sube aquí una foto o video que explique cómo evaluar esta pregunta', null=True, upload_to='ayudas_preguntas/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.CharField(blank=True, help_text='Ej: 1.1, 1.2, 2.1…', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='comentario',
            field=models.TextField(blank=True, help_text='Puedes dejar una observación o detalle extra aquí', null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Sube aquí la foto o video como evidencia de tu respuesta', null=True, upload_to='evidencias_respuestas/'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='seleccion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NA')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='AttemptAnswer',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
